# -*- coding: utf-8 -*-
"""Treino.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vmGtfG239J8rkufrf1iIh-XtTY06iQW9
"""

from google.colab import drive

drive.mount('/content/gdrive')

!ls '/content/gdrive/My Drive/TP-VC-2023'

DATA_DIR = '/content/gdrive/My Drive/TP-VC-2023'

!pip install ultralytics

import os

from ultralytics import YOLO


model = YOLO('yolov8n-seg.pt')  # load a pretrained model (recommended for training)

model.train(data='/content/gdrive/My Drive/TP-VC-2023/config2.yaml', epochs=100, imgsz=640)

import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

!scp -r /content/runs '/content/gdrive/My Drive/TP-VC-2023/ImageSegmentationYOLOv8'

"""# Nova seção"""